const keys = [
    {
        code: 'Backquote',
        ru: 'ё',
        en: '`',
        shiftRu: 'Ё',
        shiftEn: '~',
    },
    {
        code: 'Digit1',
        ru: '1',
        en: '1',
        shiftRu: '!',
        shiftEn: '!',
    },
    {
        code: 'Digit2',
        ru: '2',
        en: '2',
        shiftRu: '"',
        shiftEn: '@',
    },
    {
        code: 'Digit3',
        ru: '3',
        en: '3',
        shiftRu: '№',
        shiftEn: '#',
    },
    {
        code: 'Digit4',
        ru: '4',
        en: '4',
        shiftRu: ';',
        shiftEn: '$',
    },
    {
        code: 'Digit5',
        ru: '5',
        en: '5',
        shiftRu: '%',
        shiftEn: '%',
    },
    {
        code: 'Digit6',
        ru: '6',
        en: '6',
        shiftRu: ':',
        shiftEn: '^',
    },
    {
        code: 'Digit7',
        ru: '7',
        en: '7',
        shiftRu: '?',
        shiftEn: '&',
    },
    {
        code: 'Digit8',
        ru: '8',
        en: '8',
        shiftRu: '*',
        shiftEn: '*',
    },
    {
        code: 'Digit9',
        ru: '9',
        en: '9',
        shiftRu: '(',
        shiftEn: '(',
    },
    {
        code: 'Digit0',
        ru: '0',
        en: '0',
        shiftRu: ')',
        shiftEn: ')',
    },
    {
        code: 'Minus',
        ru: '-',
        en: '-',
        shiftRu: '_',
        shiftEn: '_',
    },
    {
        code: 'Equal',
        ru: '=',
        en: '=',
        shiftRu: '+',
        shiftEn: '+',
    },
    {
        code: 'Backspace',
        ru: 'Backspace',
        en: 'Backspace',
        shiftRu: 'Backspace',
        shiftEn: 'Backspace',
        br: true,
    },
    {
        code: 'Tab',
        ru: 'Tab',
        en: 'Tab',
        shiftRu: 'Tab',
        shiftEn: 'Tab',
    },
    {
        code: 'KeyQ',
        ru: 'й',
        en: 'q',
        shiftRu: 'Й',
        shiftEn: 'Q',
    },
    {
        code: 'KeyW',
        ru: 'ц',
        en: 'w',
        shiftRu: 'Ц',
        shiftEn: 'W',
    },
    {
        code: 'KeyE',
        ru: 'у',
        en: 'e',
        shiftRu: 'У',
        shiftEn: 'E',
    },
    {
        code: 'KeyR',
        ru: 'к',
        en: 'r',
        shiftRu: 'К',
        shiftEn: 'R',
    },
    {
        code: 'KeyT',
        ru: 'е',
        en: 't',
        shiftRu: 'Е',
        shiftEn: 'T',
    },
    {
        code: 'KeyY',
        ru: 'н',
        en: 'y',
        shiftRu: 'Н',
        shiftEn: 'Y',
    },
    {
        code: 'KeyU',
        ru: 'г',
        en: 'u',
        shiftRu: 'Г',
        shiftEn: 'U',
    },
    {
        code: 'KeyI',
        ru: 'ш',
        en: 'i',
        shiftRu: 'Ш',
        shiftEn: 'I',
    },
    {
        code: 'KeyO',
        ru: 'щ',
        en: 'o',
        shiftRu: 'Щ',
        shiftEn: 'O',
    },
    {
        code: 'KeyP',
        ru: 'з',
        en: 'p',
        shiftRu: 'З',
        shiftEn: 'P',
    },
    {
        code: 'BracketLeft',
        ru: 'х',
        en: '[',
        shiftRu: 'Х',
        shiftEn: '{',
    },
    {
        code: 'BracketRight',
        ru: 'ъ',
        en: ']',
        shiftRu: 'Ъ',
        shiftEn: '}',
    },
    {
        code: 'Backslash',
        ru: '\\',
        en: '\\',
        shiftRu: '/',
        shiftEn: '|',
        br: true,
    },
    {
        code: 'CapsLock',
        ru: 'CapsLk',
        en: 'CapsLk',
        shiftRu: 'CapsLk',
        shiftEn: 'CapsLk',
    },
    {
        code: 'KeyA',
        ru: 'ф',
        en: 'a',
        shiftRu: 'Ф',
        shiftEn: 'A',
    },
    {
        code: 'KeyS',
        ru: 'ы',
        en: 's',
        shiftRu: 'Ы',
        shiftEn: 'S',
    },
    {
        code: 'KeyD',
        ru: 'в',
        en: 'd',
        shiftRu: 'В',
        shiftEn: 'D',
    },
    {
        code: 'KeyF',
        ru: 'а',
        en: 'f',
        shiftRu: 'А',
        shiftEn: 'F',
    },
    {
        code: 'KeyG',
        ru: 'п',
        en: 'g',
        shiftRu: 'П',
        shiftEn: 'G',
    },
    {
        code: 'KeyH',
        ru: 'р',
        en: 'h',
        shiftRu: 'Р',
        shiftEn: 'H',
    },
    {
        code: 'KeyJ',
        ru: 'о',
        en: 'j',
        shiftRu: 'О',
        shiftEn: 'J',
    },
    {
        code: 'KeyK',
        ru: 'л',
        en: 'k',
        shiftRu: 'Л',
        shiftEn: 'K',
    },
    {
        code: 'KeyL',
        ru: 'д',
        en: 'l',
        shiftRu: 'Д',
        shiftEn: 'L',
    },
    {
        code: 'Semicolon',
        ru: 'ж',
        en: ';',
        shiftRu: 'Ж',
        shiftEn: ':',
    },
    {
        code: 'Quote',
        ru: 'э',
        en: "'",
        shiftRu: 'Э',
        shiftEn: '"',
    },
    {
        code: 'Enter',
        ru: 'Enter',
        en: 'Enter',
        shiftRu: 'Enter',
        shiftEn: 'Enter',
        br: true,
    },
    {
        code: 'ShiftLeft',
        ru: 'Shift',
        en: 'Shift',
        shiftRu: 'Shift',
        shiftEn: 'Shift',
    },
    {
        code: 'KeyZ',
        ru: 'я',
        en: 'z',
        shiftRu: 'Я',
        shiftEn: 'Z',
    },
    {
        code: 'KeyX',
        ru: 'ч',
        en: 'x',
        shiftRu: 'Ч',
        shiftEn: 'X',
    },
    {
        code: 'KeyC',
        ru: 'с',
        en: 'c',
        shiftRu: 'С',
        shiftEn: 'C',
    },
    {
        code: 'KeyV',
        ru: 'м',
        en: 'v',
        shiftRu: 'М',
        shiftEn: 'V',
    },
    {
        code: 'KeyB',
        ru: 'и',
        en: 'b',
        shiftRu: 'И',
        shiftEn: 'B',
    },
    {
        code: 'KeyN',
        ru: 'т',
        en: 'n',
        shiftRu: 'Т',
        shiftEn: 'N',
    },
    {
        code: 'KeyM',
        ru: 'ь',
        en: 'm',
        shiftRu: 'Ь',
        shiftEn: 'M',
    },
    {
        code: 'Comma',
        ru: 'б',
        en: ',',
        shiftRu: 'Б',
        shiftEn: '<',
    },
    {
        code: 'Period',
        ru: 'ю',
        en: '.',
        shiftRu: 'Ю',
        shiftEn: '>',
    },
    {
        code: 'Slash',
        ru: '.',
        en: '/',
        shiftRu: ',',
        shiftEn: '?',
    },
    {
        code: 'ArrowUp',
        ru: '▲',
        en: '▲',
        shiftRu: '▲',
        shiftEn: '▲',
    },
    {
        code: 'ShiftRight',
        ru: 'Shift',
        en: 'Shift',
        shiftRu: 'Shift',
        shiftEn: 'Shift',
        br: true,
    },
    {
        code: 'ControlLeft',
        ru: 'Ctrl',
        en: 'Ctrl',
        shiftRu: 'Ctrl',
        shiftEn: 'Ctrl',
    },
    {
        code: 'AltLeft',
        ru: 'Alt',
        en: 'Alt',
        shiftRu: 'Alt',
        shiftEn: 'Alt',
    },
    {
        code: 'Space',
        ru: 'Space',
        en: 'Space',
        shiftRu: 'Space',
        shiftEn: 'Space',
    },
    {
        code: 'AltRight',
        ru: 'Alt',
        en: 'Alt',
        shiftRu: 'Alt',
        shiftEn: 'Alt',
    },
    {
        code: 'ControlRight',
        ru: 'Ctrl',
        en: 'Ctrl',
        shiftRu: 'Ctrl',
        shiftEn: 'Ctrl',
    },
    {
        code: 'ArrowLeft',
        ru: '◄',
        en: '◄',
        shiftRu: '◄',
        shiftEn: '◄',
    },
    {
        code: 'ArrowDown',
        ru: '▼',
        en: '▼',
        shiftRu: '▼',
        shiftEn: '▼',
    },
    {
        code: 'ArrowRight',
        ru: '►',
        en: '►',
        shiftRu: '►',
        shiftEn: '►',
    },
    {
        code: 'Lang',
        ru: 'RU',
        en: 'EN',
        shiftRu: 'RU',
        shiftEn: 'EN',
    },
];

export default keys;
